Repository ultralytics/yolo-ios-app, pull requests merged in 2024-08, with the labels that each got.

#52 Update format.yml
  .github/workflows/format.yml
Labels: dependencies, enhancement

#54 Enable Swift formatting in Ultralytics Actions
  .github/workflows/format.yml
Labels: enhancement

#55 Run new Swift formatting
  .github/workflows/format.yml
  YOLO/AppDelegate.swift
  YOLO/Utilities/BoundingBoxView.swift
  YOLO/Utilities/ThresholdProvider.swift
  YOLO/VideoCapture.swift
  YOLO/ViewController.swift
Labels: dependencies, enhancement

#57 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: dependencies, documentation, enhancement

#59 Add https://www.reddit.com/r/Ultralytics/ badge
  README.md
Labels: documentation, enhancement
