Repository ultralytics/yolo-ios-app, pull requests merged in 2025-08, with the labels that each got.

#129 Fix warnings
  ExampleApps/README.md
  YOLOiOSApp/YOLOiOSApp.xcodeproj/project.pbxproj
  YOLOiOSApp/YOLOiOSApp.xcodeproj/xcshareddata/xcschemes/YOLOiOSApp.xcscheme
  YOLOiOSApp/YOLOiOSApp/Info.plist
  YOLOiOSApp/YOLOiOSApp/ModelDownloadManager.swift
  YOLOiOSApp/YOLOiOSApp/ViewController.swift
Labels: enhancement, embedded

#128 Update README App Store Previews
  README.md
  YOLOiOSApp/README.md
Labels: documentation

#131 Improved model download bash script
  .github/workflows/ci.yml
  Tests/YOLOTests/Resources/README.md
  Tests/YOLOTests/Resources/download-test-models.sh
  YOLOiOSApp/YOLOiOSApp/Info.plist
  scripts/download-models.sh
Labels: documentation, enhancement, devops

#132 Fix Xcode Cloud build directory issues
  ExampleApps/YOLORealTimeUIKit/YOLORealTimeUIKit.xcodeproj/project.pbxproj
  ExampleApps/YOLOSingleImageSwiftUI/YOLOSingleImageSwiftUI.xcodeproj/project.pbxproj
  YOLOiOSApp/YOLOiOSApp.xcodeproj/project.pbxproj
  YOLOiOSApp/YOLOiOSApp/Info.plist
  YOLOiOSApp/YOLOiOSApp/Main.storyboard
Labels: enhancement, devops

#133 Download models for app as well as tests
  .github/workflows/publish.yml
Labels: enhancement, devops

#143 Fixed access modifiers for OBBResult
  Sources/YOLO/YOLOResult.swift
Labels: enhancement, OBB

#151 Cleanup publish.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#154 Update ci.yml to macos-latest
  .github/workflows/ci.yml
Labels: enhancement, devops

#156 Squash commits into `testflight`
  .github/workflows/publish.yml
  YOLOiOSApp/YOLOiOSApp/Info.plist
Labels: enhancement, devops

#157 Simplify publish.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#155 Change all ExampleApp default models to nano
  ExampleApps/YOLORealTimeSwiftUI/YOLORealTimeSwiftUI/ContentView.swift
  ExampleApps/YOLOSingleImageSwiftUI/YOLOSingleImageSwiftUI/ContentView.swift
  ExampleApps/YOLOSingleImageUIKit/YOLOSingleImageUIKit/ViewController.swift
Labels: enhancement, detect, embedded

#159 Update format.yml for Swift formatting
  .github/workflows/format.yml
  Sources/YOLO/BasePredictor.swift
  Sources/YOLO/Plot.swift
  Sources/YOLO/Segmenter.swift
  Sources/YOLO/VideoCapture.swift
  Sources/YOLO/YOLOView.swift
  Tests/YOLOTests/BasePredictorTests.swift
  Tests/YOLOTests/PlotTests.swift
  Tests/YOLOTests/ThresholdProviderTests.swift
  Tests/YOLOTests/YOLOIntegrationTests.swift
  Tests/YOLOTests/YOLOMainTests.swift
  Tests/YOLOTests/YOLOResultTests.swift
  Tests/YOLOTests/YOLOTaskTests.swift
  YOLOiOSApp/YOLOiOSApp/ModelDownloadManager.swift
  YOLOiOSApp/YOLOiOSApp/ViewController.swift
Labels: enhancement, devops

#140 Clean model download migration
  .github/workflows/ci.yml
  Package.swift
  Sources/YOLO/README.md
  Sources/YOLO/YOLO.swift
  Sources/YOLO/YOLOCamera.swift
  Sources/YOLO/YOLOModelCache.swift
  Sources/YOLO/YOLOModelDownloader.swift
  YOLOiOSApp/YOLOiOSApp.xcodeproj/project.pbxproj
  YOLOiOSApp/YOLOiOSApp/Info.plist
  YOLOiOSApp/YOLOiOSApp/ModelDownloadManager.swift
  YOLOiOSApp/YOLOiOSApp/ViewController.swift
Labels: enhancement, detect, segment

#169 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: devops
