Repository ultralytics/yolo-ios-app, pull requests merged in 2025-01, with the labels that each got.

#74 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#75 Fix spelling in Main.storyboard
  YOLO/Main.storyboard
  YOLO/ViewController.swift
Labels: documentation

#68 Front camera
  YOLO/Info.plist
  YOLO/Main.storyboard
  YOLO/VideoCapture.swift
  YOLO/ViewController.swift
Labels: documentation, enhancement, detect

#79 Standardize license headers in TOML/YAML files
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/tag.yml
Labels: documentation, devops
